/* eslint-disable no-undef */
const API_BASE_URL_DEVELOPMENT = 'https://localhost:7222';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';


const ENDPOINTS = {
    GET_ALL_POST: 'get-all-post',
    GET_ALL_POST_BY_ID: 'get-post',
    CREATE_POST: 'create-post',
    UPDATE_POST: 'update-post',
    DELETE_POST: 'delete-post'
}

const Development = {
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_POST}`,
    API_URL_GET_ALL_POSTS_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_POST}`
}


const Production = {
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_POST}`,
    API_URL_GET_ALL_POSTS_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_POST}`
}


const Sabitler = process.env.NODE_ENV === 'development' ? Development : Production

export default Sabitler; 